name: Rust OpenGL CI

on:
  push:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install OpenGL
        run: |
          sudo apt-get update
          # opengl dependencies
          sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
          # glfw dependencies
          #sudo apt-get install libglfw3-dev libglfw3
          # glfw dependencies
          sudo apt-get install xorg-dev

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run linter
        uses: actions-rs/cargo@v1
        with:
          command: clippy
