name: Rust OpenGL CI

on:
  push:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            /etc/apt/
          key: apt-v1

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install OpenGL
        run: |
          sudo apt-get update
          sudo apt-get install mesa-utils xvfb xorg-dev

      - name: Run tests
        run: |
          echo "OpenGL Version Info:"
          xvfb-run --auto-servernum glxinfo | grep OpenGL | grep -v extensions
          
          echo ""
          echo "Run tests:"
          xvfb-run --auto-servernum cargo test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: render-tests
          path: assets/tests/*.png
          if-no-files-found: error
          retention-days: 1

      - name: Run linter
        uses: actions-rs/cargo@v1
        with:
          command: clippy
